apiVersion: apps/v1
kind: Deployment
metadata:
  name: trend-node-deployment
  labels:
    app: trend-node-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: trend-node-app
  template:
    metadata:
      labels:
        app: trend-node-app
    spec:
      containers:
        - name: trend-node-container
          image: saran0702/trend-app:latest   #final fix
          imagePullPolicy: Always
          ports:
            - containerPort: 3000         #fixed
          env:
            - name: PORT
              value: "3000"
