apiVersion: v1
kind: Service
metadata:
  name: trend-node-service
spec:
  type: LoadBalancer
  selector:
    app: trend-node-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000   #MUST be 3000