pipeline {
    agent any

    environment {
        DOCKER_IMAGE = "saran0702/trend-app:v1"
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Docker Build') {
            steps {
                sh 'docker build -t $DOCKER_IMAGE ./app'
            }
        }

        stage('Docker Push') {
            steps {
                sh 'docker push $DOCKER_IMAGE'
            }
        }
    }

    post {
        success {
            echo "SUCCESS ✅ Image pushed to DockerHub"
        }
        failure {
            echo "FAILED ❌ Check logs"
        }
    }
}
